# Generated by Django 2.0.7 on 2019-07-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_id', models.UUIDField(verbose_name='编号')),
                ('ps_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='大货单号')),
                ('ps_date', models.DateField(blank=True, null=True, verbose_name='大货交期')),
                ('ps_confirm_date', models.DateField(blank=True, null=True, verbose_name='大货确认时间')),
                ('ps_arrival_date', models.DateField(blank=True, null=True, verbose_name='面料到货')),
                ('ps_tailor_date', models.DateField(blank=True, null=True, verbose_name='裁剪时间')),
                ('ps_embroider_date', models.DateField(blank=True, null=True, verbose_name='绣花时间')),
                ('ps_print_date', models.DateField(blank=True, null=True, verbose_name='印花时间')),
                ('ps_water_washing_date', models.DateField(blank=True, null=True, verbose_name='水洗时间')),
                ('ps_sewing_date', models.DateField(blank=True, null=True, verbose_name='车缝时间')),
                ('ps_ingredients_fabric_arrival_date', models.DateField(blank=True, null=True, verbose_name='辅料到货')),
                ('ps_tags_arrival_date', models.DateField(blank=True, null=True, verbose_name='吊牌到货')),
                ('ps_iron_package_date', models.DateField(blank=True, null=True, verbose_name='整烫包装')),
                ('ps_outward_transport_date', models.DateField(blank=True, null=True, verbose_name='外运时间')),
                ('ps_gathering_date', models.DateField(blank=True, null=True, verbose_name='收款时间')),
                ('ps_gathering_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='收款金额')),
                ('ps_contract_balance', models.CharField(blank=True, max_length=200, null=True, verbose_name='合同金额')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '大货表',
                'verbose_name_plural': '大货表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductionWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_id', models.UUIDField(verbose_name='编号')),
                ('pw_workshop', models.CharField(blank=True, max_length=200, null=True, verbose_name='生产车间')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '生产车间表',
                'verbose_name_plural': '生产车间表',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='ps_workshop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionWorkshop', verbose_name='生产车间'),
        ),
    ]
