# Generated by Django 2.0.7 on 2019-07-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionWorkshop', verbose_name='生产车间'),
        ),
    ]
