# Generated by Django 2.0.7 on 2019-07-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0002_auto_20190704_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='ps_end',
            field=models.BooleanField(default=False, verbose_name='大货是否结束/默认结束'),
        ),
    ]
