# Generated by Django 2.0.7 on 2019-05-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0002_auto_20190517_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到料时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_contract_balance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合同余额'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_gathering_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收款金额'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_price_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='金额类型'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionWorkshop', verbose_name='生产车间'),
        ),
    ]
