# Generated by Django 2.0.7 on 2019-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0003_auto_20190518_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_Water_washing_date',
            field=models.DateField(blank=True, null=True, verbose_name='水洗时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='到料时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_embroider_date',
            field=models.DateField(blank=True, null=True, verbose_name='绣花时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_gathering_date',
            field=models.DateField(blank=True, null=True, verbose_name='收款时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_outward_transport_date',
            field=models.DateField(blank=True, null=True, verbose_name='外运时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_print_date',
            field=models.DateField(blank=True, null=True, verbose_name='印花时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_qc_date',
            field=models.DateField(blank=True, null=True, verbose_name='QC时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_sewing_date',
            field=models.DateField(blank=True, null=True, verbose_name='车缝时间'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='ps_tailor_date',
            field=models.DateField(blank=True, null=True, verbose_name='裁剪时间'),
        ),
    ]
