# Generated by Django 2.0.7 on 2019-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0004_auto_20190529_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='ps_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='大货单号'),
        ),
    ]
