# Generated by Django 2.0.7 on 2019-06-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0005_productionschedule_ps_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionschedule',
            old_name='ps_Water_washing_date',
            new_name='ps_water_washing_date',
        ),
    ]
