# Generated by Django 2.0.7 on 2019-05-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proofing_progress', '0001_initial'),
        ('user', '0001_initial'),
        ('production_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.UUIDField(verbose_name='编号')),
                ('ad_type', models.CharField(max_length=200, verbose_name='后扣')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '后扣',
                'verbose_name_plural': '后扣',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.UUIDField(verbose_name='编号')),
                ('cc_color', models.CharField(max_length=200, verbose_name='颜色')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '颜色',
                'verbose_name_plural': '颜色',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapEyebrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_id', models.UUIDField(verbose_name='编号')),
                ('ce_type', models.CharField(max_length=200, verbose_name='帽眉')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '帽眉',
                'verbose_name_plural': '帽眉',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_id', models.UUIDField(verbose_name='编号')),
                ('ct_type', models.CharField(max_length=200, verbose_name='帽型')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '帽型',
                'verbose_name_plural': '帽型',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.UUIDField(verbose_name='编号')),
                ('c_name', models.CharField(max_length=200, verbose_name='客户名')),
                ('c_contack', models.CharField(max_length=200, verbose_name='联系人')),
                ('c_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '客人',
                'verbose_name_plural': '客人',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.UUIDField(verbose_name='编号')),
                ('o_number', models.CharField(max_length=200, verbose_name='订单号')),
                ('o_data', models.DateField(verbose_name='订单日期')),
                ('o_image', models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='图片')),
                ('o_embroiderorprint', models.IntegerField(choices=[(0, '无'), (1, '绣花'), (2, '印花')], verbose_name='绣印花')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('o_afterdeduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.AfterDeduction', verbose_name='后扣')),
                ('o_capcolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.CapColor', verbose_name='颜色')),
                ('o_capeyebrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.CapEyebrow', verbose_name='帽眉')),
                ('o_captype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.CapType', verbose_name='帽型')),
                ('o_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_id', models.UUIDField(verbose_name='编号')),
                ('pi_amount', models.IntegerField(verbose_name='下单数量')),
                ('pi_price_type', models.CharField(max_length=50, verbose_name='单价类型')),
                ('pi_unit_price', models.CharField(max_length=100, verbose_name='下单单价')),
                ('pi_date', models.DateField(verbose_name='交货日期')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '大货信息',
                'verbose_name_plural': '大货信息',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VersionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_id', models.UUIDField(verbose_name='编号')),
                ('vn_version', models.CharField(max_length=200, verbose_name='版号')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '版号',
                'verbose_name_plural': '版号',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='o_productinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_information.ProductInfo', verbose_name='大货信息'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_productionschedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionSchedule', verbose_name='大货进度'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_proofingprogress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proofing_progress.ProofingProgress', verbose_name='打样进度'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='业务员'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_versionnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_information.VersionNumber', verbose_name='版号'),
        ),
    ]
