# Generated by Django 2.0.7 on 2019-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='订单日期'),
        ),
    ]
