# Generated by Django 2.0.7 on 2019-05-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0002_auto_20190516_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_afterdeduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.AfterDeduction', verbose_name='后扣'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_capcolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.CapColor', verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_capeyebrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.CapEyebrow', verbose_name='帽眉'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_captype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.CapType', verbose_name='帽型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.Customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_embroiderorprint',
            field=models.IntegerField(blank=True, choices=[(0, '无'), (1, '绣花'), (2, '印花')], null=True, verbose_name='绣印花'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_productinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.ProductInfo', verbose_name='大货信息'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_productionschedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionSchedule', verbose_name='大货进度'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_proofingprogress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proofing_progress.ProofingProgress', verbose_name='打样进度'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_versionnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.VersionNumber', verbose_name='版号'),
        ),
    ]
