# Generated by Django 2.0.7 on 2019-05-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0003_auto_20190518_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_data',
            new_name='o_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='o_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='业务员'),
        ),
    ]
