# Generated by Django 2.0.7 on 2019-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0005_auto_20190518_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
