# Generated by Django 2.0.7 on 2019-05-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0006_auto_20190519_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbroiderOrPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eop_id', models.UUIDField(verbose_name='编号')),
                ('eop_type', models.CharField(max_length=200, verbose_name='绣印花')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '绣印花',
                'verbose_name_plural': '绣印花',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='o_embroiderorprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.EmbroiderOrPrint', verbose_name='绣印花'),
        ),
    ]
