# Generated by Django 2.0.7 on 2019-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0007_auto_20190529_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_date',
            field=models.DateField(blank=True, null=True, verbose_name='订单日期'),
        ),
    ]
