# Generated by Django 2.0.7 on 2019-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0008_auto_20190529_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_proofingprogress_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='打样数量'),
        ),
    ]
