# Generated by Django 2.0.7 on 2019-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0009_order_o_proofingprogress_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='o_capcolor',
        ),
        migrations.AddField(
            model_name='order',
            name='o_capcolor',
            field=models.ManyToManyField(blank=True, null=True, to='order_information.CapColor', verbose_name='颜色'),
        ),
    ]
