# Generated by Django 2.0.7 on 2019-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0011_auto_20190604_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pi_embroider_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='绣花报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_fabric_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='面料报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_ingredients_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='辅料报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_labor_payment_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工缴报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_other_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='其他报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_packaging_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装物报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_print_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='印花报价'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_reserved_profits',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预留利润'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_total_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大货总金额'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='pi_water_washing_quotation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='水洗报价'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pi_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='大货数量'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pi_price_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='价格类型'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pi_unit_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大货报价'),
        ),
    ]
