# Generated by Django 2.0.7 on 2019-06-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0013_auto_20190614_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='pt_type_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
