# Generated by Django 2.0.7 on 2019-06-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0014_pricetype_pt_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_capcolor',
            field=models.ManyToManyField(blank=True, to='order_information.CapColor', verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_proofingprogress',
            field=models.ManyToManyField(blank=True, to='proofing_progress.ProofingProgress', verbose_name='打样进度'),
        ),
    ]
