# Generated by Django 2.0.7 on 2019-06-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0015_auto_20190617_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pi_offer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大货报价'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pi_unit_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大货单价'),
        ),
    ]
