# Generated by Django 2.0.7 on 2019-06-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0016_auto_20190618_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.UUIDField(verbose_name='编号')),
                ('ad_total_profit', models.CharField(blank=True, max_length=100, null=True, verbose_name='利润总金额')),
                ('ad_fabric_ingredients_total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='面辅料金额')),
                ('ad_fabric_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='面料金额')),
                ('ad_fabric_express_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='面料快递金额')),
                ('ad_bonding_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='粘合金额')),
                ('ad_ingredients_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='辅料金额')),
                ('ad_ingredients_express_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='辅料快递金额')),
                ('ad_fabric_ingredients_other_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='面辅料其他金额')),
                ('ad_labor_paymentl_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='工缴金额')),
                ('ad_tailor_total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='裁剪总金额')),
                ('ad_tailor_start_date', models.DateTimeField(blank=True, null=True, verbose_name='裁剪开始时间')),
                ('ad_tailor_end_date', models.DateTimeField(blank=True, null=True, verbose_name='裁剪结束时间')),
                ('ad_tailor_number_people', models.IntegerField(blank=True, null=True, verbose_name='裁剪人数')),
                ('ad_sewing_total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='车缝总金额')),
                ('ad_sewing_start_date', models.DateTimeField(blank=True, null=True, verbose_name='车缝开始时间')),
                ('ad_sewing_end_date', models.DateTimeField(blank=True, null=True, verbose_name='车缝结束时间')),
                ('ad_sewing_number_people', models.IntegerField(blank=True, null=True, verbose_name='车缝人数')),
                ('ad_iron_total_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='整烫总金额')),
                ('ad_iron_start_date', models.DateTimeField(blank=True, null=True, verbose_name='整烫开始时间')),
                ('ad_iron_end_date', models.DateTimeField(blank=True, null=True, verbose_name='整烫结束时间')),
                ('ad_iron_number_people', models.IntegerField(blank=True, null=True, verbose_name='整烫人数')),
                ('ad_embroide_print_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='绣印花金额')),
                ('ad_water_washing_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='水洗金额')),
                ('ad_embroide_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='绣花金额')),
                ('ad_print_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='印花金额')),
                ('ad_packaging_shipping_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='包装船务金额')),
                ('ad_paperboard_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='纸板金额')),
                ('ad_physical_distribution_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流金额')),
                ('ad_warehouse_entry_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='进仓金额')),
                ('ad_customs_declaration_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='报关金额')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '按单核算',
                'verbose_name_plural': '按单核算',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='o_accountingdocuments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_information.Accounting_Documents', verbose_name='按单核算'),
        ),
    ]
