# Generated by Django 2.0.7 on 2019-06-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_information', '0017_auto_20190618_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounting_Documents',
            new_name='AccountingDocuments',
        ),
    ]
