# Generated by Django 2.0.7 on 2019-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofing_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofingprogress',
            name='pp_end',
            field=models.BooleanField(default=False, verbose_name='本次打样是否完成/默认未完成'),
        ),
    ]
