# Generated by Django 2.0.7 on 2019-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofing_progress', '0002_auto_20190517_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_Modify_sample_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='到料时间（修改）'),
        ),
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_Modify_sample_express_date',
            field=models.DateField(blank=True, null=True, verbose_name='快递时间（修改）'),
        ),
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_Modify_sample_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单时间（修改）'),
        ),
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_sample_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='到料时间'),
        ),
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_sample_express_date',
            field=models.DateField(blank=True, null=True, verbose_name='快递时间'),
        ),
        migrations.AlterField(
            model_name='proofingprogress',
            name='pp_sample_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='下单时间'),
        ),
    ]
