# Generated by Django 2.0.7 on 2019-06-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofing_progress', '0003_auto_20190529_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofingprogress',
            name='pp_Modify_sample_arrival_date',
        ),
        migrations.RemoveField(
            model_name='proofingprogress',
            name='pp_Modify_sample_express_date',
        ),
        migrations.RemoveField(
            model_name='proofingprogress',
            name='pp_Modify_sample_order_date',
        ),
    ]
