# Generated by Django 2.0.7 on 2019-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='ab_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='b',
            name='b_end',
            field=models.BooleanField(default=False),
        ),
    ]
