# Generated by Django 2.0.7 on 2019-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190625_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='a_b',
        ),
        migrations.AddField(
            model_name='a',
            name='a_b',
            field=models.ManyToManyField(blank=True, null=True, to='demo.B'),
        ),
    ]
