# Generated by Django 2.0.7 on 2019-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(verbose_name='编号')),
                ('u_name', models.CharField(max_length=200, verbose_name='用户名')),
                ('u_username', models.CharField(max_length=200, verbose_name='账号')),
                ('u_password', models.CharField(max_length=200, verbose_name='密码')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'ordering': ['pk'],
            },
        ),
    ]
