# Generated by Django 2.0.7 on 2019-06-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.UUIDField(verbose_name='编号')),
                ('ad_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='后扣')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '后扣表',
                'verbose_name_plural': '后扣表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.UUIDField(verbose_name='编号')),
                ('cc_color', models.CharField(blank=True, max_length=200, null=True, verbose_name='颜色')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '帽子颜色表',
                'verbose_name_plural': '帽子颜色表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapEyebrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_id', models.UUIDField(verbose_name='编号')),
                ('ce_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='帽眉')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '帽眉表',
                'verbose_name_plural': '帽眉表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_id', models.UUIDField(verbose_name='编号')),
                ('ct_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='帽型')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '帽型表',
                'verbose_name_plural': '帽型表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.UUIDField(verbose_name='编号')),
                ('c_name', models.CharField(max_length=200, verbose_name='客户名')),
                ('c_contack', models.CharField(max_length=200, verbose_name='联系人')),
                ('c_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '客户表',
                'verbose_name_plural': '客户表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EmbroiderOrPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eop_id', models.UUIDField(verbose_name='编号')),
                ('eop_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='绣印花')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '绣印花表',
                'verbose_name_plural': '绣印花表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.UUIDField(verbose_name='编号')),
                ('o_customer_number', models.CharField(max_length=200, verbose_name='客户款号')),
                ('o_date', models.DateField(blank=True, null=True, verbose_name='下单日期')),
                ('o_price_type', models.CharField(default='￥', max_length=200, verbose_name='人民币单位')),
                ('o_dollar_type', models.CharField(default='$', max_length=200, verbose_name='美金单位')),
                ('o_count', models.IntegerField(blank=True, null=True, verbose_name='颜色数量')),
                ('o_image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='图片')),
                ('o_file', models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='文件')),
                ('o_main_fabric', models.CharField(blank=True, max_length=200, null=True, verbose_name='主面料')),
                ('o_ps_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='大货单价')),
                ('o_dollar_exchange_rate', models.CharField(blank=True, default='6.9', max_length=200, null=True, verbose_name='美元汇率')),
                ('o_dollar_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='美元单价')),
                ('o_ps_amount', models.CharField(blank=True, max_length=200, null=True, verbose_name='大货数量')),
                ('o_ps_dollar_total_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='大货总金额（美元）')),
                ('o_delivery_date', models.DateField(blank=True, null=True, verbose_name='交货期')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('o_afterdeduction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.AfterDeduction', verbose_name='后扣')),
                ('o_capcolor', models.ManyToManyField(blank=True, to='order.CapColor', verbose_name='颜色')),
                ('o_capeyebrow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CapEyebrow', verbose_name='帽眉')),
                ('o_captype', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CapType', verbose_name='帽型')),
                ('o_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='客户')),
                ('o_embroiderorprint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.EmbroiderOrPrint', verbose_name='绣印花')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='VersionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vn_id', models.UUIDField(verbose_name='编号')),
                ('vn_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='版号')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_end_date', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '版号表',
                'verbose_name_plural': '版号表',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='o_versionnumber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.VersionNumber', verbose_name='版号'),
        ),
    ]
