# Generated by Django 2.0.7 on 2019-07-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_o_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_afterdeduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.AfterDeduction', verbose_name='后扣'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_capeyebrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CapEyebrow', verbose_name='帽眉'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_captype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CapType', verbose_name='帽型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_embroiderorprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.EmbroiderOrPrint', verbose_name='绣印花'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='业务员'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_versionnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.VersionNumber', verbose_name='版号'),
        ),
    ]
