# Generated by Django 2.0.7 on 2019-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190702_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_pp_all_end',
            field=models.BooleanField(default=False, verbose_name='打样是否完成/默认未完成'),
        ),
    ]
