# Generated by Django 2.0.7 on 2019-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_o_pp_all_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_proofingprogress',
            field=models.ManyToManyField(blank=True, to='proofing_progress.ProofingProgress', verbose_name='打样'),
        ),
    ]
