# Generated by Django 2.0.7 on 2019-07-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_schedule', '0001_initial'),
        ('order', '0007_auto_20190703_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_productionschedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_schedule.ProductionSchedule', verbose_name='大货表'),
        ),
    ]
