# Generated by Django 2.0.7 on 2019-07-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        ('order', '0008_order_o_productionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.Quotation', verbose_name='报价单表'),
        ),
    ]
