# Generated by Django 2.0.7 on 2019-07-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_documents', '0001_initial'),
        ('order', '0009_order_o_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_accountingdocuments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_documents.AccountingDocuments', verbose_name='核算单表'),
        ),
    ]
